### ISSUE TITLE
Dynamic linking causes crash

### ISSUE THREAD

**Issue by rvandertogt** [ChaiScript/ChaiScript#157]
Hi,

When i run the dynamically linked code (VS2013,chaiscript_stdlib-5.6.0.dll) my application crashes at load_module.

![image](https://cloud.githubusercontent.com/assets/10296345/6481194/bc383a90-c25b-11e4-8f75-ae1ace05cdff.png)

Static linking is working fine but I would like to use the dynamic loading.

**Comment by lefticus** [comment]
The automated tests (posted here: http://chaiscript.com/ChaiScript-BuildResults/full_dashboard.html) fully test both static and dynamic linking of the stdlib. So I'm certain it's not a systemic issue.

The stack trace of the crash would be more valuable than the locals, so if you can post a stack trace, that'd be good.

Otherwise, C++ is very sensitive to the compilation flags when dynamically loading modules. 

Are you using the DLL provided by the download package, or are you compiling it yourself? Any difference such as unicode / debug / release / 64bit vs 32bit could cause this crash.

**Comment by rvandertogt** [comment]
Hi Jason,

 

I was using the precompiled DLL. Build it using the same settings as my
other DLL's and it is working fine.

 

Thanks for the quick reply...and for ChaiScript, it is the best!

By the way, why is it called ChaiScript?

 

Met vriendelijke groet,

Reinier van der Togt




  _____  

Van: Jason Turner [mailto:notifications@github.com] 
Verzonden: woensdag 4 maart 2015 14:52
Aan: ChaiScript/ChaiScript
CC: Reinier van der Togt
Onderwerp: Re: [ChaiScript] Dynamic linking causes crash (#157)

 

The automated tests (posted here:
http://chaiscript.com/ChaiScript-BuildResults/full_dashboard.html) fully
test both static and dynamic linking of the stdlib. So I'm certain it's not
a systemic issue.

The stack trace of the crash would be more valuable than the locals, so if
you can post a stack trace, that'd be good.

Otherwise, C++ is very sensitive to the compilation flags when dynamically
loading modules. 

Are you using the DLL provided by the download package, or are you compiling
it yourself? Any difference such as unicode / debug / release / 64bit vs
32bit could cause this crash.

-
Reply to this email directly or view
<https://github.com/ChaiScript/ChaiScript/issues/157#issuecomment-77160538>
it on GitHub.
<https://github.com/notifications/beacon/AJ0cGWjQNzDWg6fUc2dE8ZFQ7SPDEaofks5
nxwVvgaJpZM4DpQif.gif>

**Comment by lefticus** [comment]
ChaiScript is kind of a play on JavaScript. Chai / Tea vs Java / Coffee. There's not a whole lot of meaning to it. So can we close this issue then? You have resolved the problem?

**Comment by rvandertogt** [comment]
absolutely. we are big fans of chai
