### ISSUE TITLE
Compiling on clang-3.5

### ISSUE THREAD

**Issue by N1xx1** [ChaiScript/ChaiScript#171]
Having troubles compiling on clang, here is the log.

http://pastebin.com/jzH7Pprr

I think it's due to the fact this is a header only lib, but still I haven't seen any error like this. Any ideas?

**Comment by lefticus** [comment]
I actually compile regularly on clang, so that's probably not the problem. It might be if you the standard library you are compiling against. This error looks very similar to an error I saw while trying to build chaiscript with emcriptem.

If you are buliding with the standard CMakeLists.txt, could you try and disable the "USE_LIBCXX" option and let me know if that makes any difference?

Also, please give me every detail about the OS/standardlib that you have.

Thanks.

**Comment by N1xx1** [comment]
No, I'm not using cmake but a qmake to build. Yes, I'm using libc++, I'll try to disable it, but it may be a problem since I'm actually using some C++14 features in my code.

I'm on Ubuntu 14.04 and the libc++ version is 3.5.

**Comment by N1xx1** [comment]
Ok, tried without libc++ and it's working, but as I said, that mostly isn't a solution for me.
I'll be waiting for you to add the support :D

Also, keep up the good work, this is amazing!

**Comment by lefticus** [comment]
I did a hack to get it building in emscriptem, but thought the problem was specific to emscriptem's std lib. I know technically I'm breaking the standard by using a type inside of a map before the type is fully defined, kind of like this:

```
class Type
{
  std::map<std::string, Type> myMap;
};
```

Only libc++ complains only non-MacOS. Which is odd and all the more reason I don't trust Mac's toolchain (they have a version of clang that doesn't match any actually released version and you have no idea what patches they have applied). But that's a different issue.

Anyhow, I'll get it fixed. It needs to be fixed. Probably today, but it will be a few weeks before it gets into a release still. The current develop is stable on all platforms and has many little fixes and feature improvements, so I *can* recommend moving to it once I get your libc++ issue fixed.

**Comment by lefticus** [comment]
@N1xx1 It looks like the version of libc++ that ships with ubuntu 14.04 has some seriously broken conversions between `std::function` and lambdas and `std::bind` return values. ChaiScript relies heavily on these things.

I'm still working on it.

**Comment by lefticus** [comment]
@N1xx1 It's not possible. The `std::function` and `type_traits` implementations seem to be fundamentally broken in the version of libc++ that ships with 14.04.

Example:

```c++
#include <functional>
#include <string>

void fun(int &i, float j)
{
  i = 2;
}

class MyClass
{
  public:
    std::string getValue1() {
      return "bob";
    }

    std::string getValue() const {
      return "bob";
    }
};

int main()
{
  int j = 3;

  std::function<std::string (MyClass *)> f1(&MyClass::getValue1);
  std::function<std::string (const MyClass *)> f(&MyClass::getValue);
}
```

The first line, for the non-const function wrapper to the `getValue1` member compiles fine. The second line for the const function `getValue`, fails to compile. It works on every configuration *except* for clang with libc++ on ubuntu 14.04.

It seems to be a bug in the `is_member_function_pointer` type_trait for const-member-function-pointers. I spent several hours today trying to find a workaround to this bug and haven't been able to.

If you have a way of installing a newer version of libc++ on 14.04, let me know, and I'll give that a try. I wasn't able to find any pre-built debian packages for it.

-Jason

**Comment by lefticus** [comment]
Ok @N1xx1 one more update. It seems I can wrap the call in a lambda function and that does work. I'm going to play with this and see if I can hack up something.

I'm mainly still continuing down this road because I believe that if I can get this working I can simplify my function registration code across the board.

**Comment by lefticus** [comment]
One final note: I do have this working now. I'm running it through my automated build system to see what happens. It took some changes, but nothing huge.

**Comment by N1xx1** [comment]
Thank you, I'll test as soon as possible.
