### ISSUE TITLE
Cannot use chaiscript 5.7  in VS 2012

### ISSUE THREAD

**Issue by deltamish** [ChaiScript/ChaiScript#187]
Hi,

I came across chaiscript a few days ago and i was very impressed by it.. I wanted to try it desperately.. 
So I downloaded the package and included the header files chaiscript.hpp .. And didnot add any function to make sure that my linking was correct 
But when i try to build there are about 149 errors .. Related to cahi script 

Error	1	error C2143: syntax error : missing ',' before '...'	c:\chaiscript 5.7.0\include\chaiscript\chaiscript_defines.hpp	66
Error	2	error C2065: 'Arg' : undeclared identifier	c:\chaiscript 5.7.0\include\chaiscript\chaiscript_defines.hpp	67
Error	3	error C2988: unrecognizable template declaration/definition	c:\chaiscript 5.7.0\include\chaiscript\chaiscript_defines.hpp	67
Error	4	error C2059: syntax error : '...'	c:\chaiscript 5.7.0\include\chaiscript\chaiscript_defines.hpp	67
Error	5	error C2143: syntax error : missing ';' before '}'	c:\chaiscript 5.7.0\include\chaiscript\chaiscript_defines.hpp	76
Error	6	error C2065: 'default' : undeclared identifier	c:\chaiscript 5.7.0\include\chaiscript\dispatchkit\type_info.hpp	50
Error	7	error C2253: 'Type_Info' : pure specifier or abstract override specifier only allowed on virtual function	c:\chaiscript 5.7.0\include\chaiscript\dispatchkit\type_info.hpp	50
............... and list goes on..

Source.cpp
#include<iostream>
#include<algorithm>
#include<chaiscript/chaiscript.hpp>

int main(char* argc,int atgv)
{
	
	
	return 0;
}

![errors_chai](https://cloud.githubusercontent.com/assets/9283808/8147922/8ddcd620-12a0-11e5-9df1-326f2e9ec01e.jpg)

**Comment by lefticus** [comment]
This is due to limitations with Visual Studio, and it is impossible for me to work with VS2012 because of missing C++11 features. I'm actually surprised that it let you compile at all - the CMake configuration has an explicit check to make sure you are running an appropriate compiler on Windows.

If you absolutely must use VS2012, then you have to go back to the ChaiScript 4.x releases. Those releases require Boost.

I **strongly** recommend that you instead use at least VS2013 Update 4. VS2013 has a very good and free "community edition" that works quite well.

https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx

Here is the grid of currently supported compilers: 

http://chaiscript.com/ChaiScript-BuildResults/full_dashboard.html

Please note that Visual Studio version 12 is the one that is called "Visual Studio 2013"
Visual Studio version 14 is called "Visual Studio 2015."

**Comment by deltamish** [comment]
Hi thank you so much .. For replying so quickly ... But for vs 2012 there
was a update .. Which updated to c++ 11 ....... So it should work right ?
Can you be kind enough to clarify the doubt.

Thanks

**Comment by lefticus** [comment]
There is some support for C++11 in VS2012, but even with the updates and patches it still does not support variadic templates, which is critical for ChaiScript support.

Due to bugs in the Visual Studio compilers, I cannot guarantee that anything before VS 2013 Update 4 will work. The first release of VS2013 would probably compile it, but has known crashes with ChaiScript due to the handling of initializer lists.

**Comment by deltamish** [comment]
>
> Hi
>

I download vs 2013 and updated it to version 4..I tried a very basic
example.. It compiles perfectly..
But when it tries to run it.. It throws a execption about not able load
module

*at line 795 * in *chaiscript_engine.hpp*

throw chaiscript::exception::load_module_error("Unable to find module:
" + t_module_name + " Errors: " + errstring);


The code i am using is

#include<iostream>#include <chaiscript\chaiscript.hpp>#include
<chaiscript\chaiscript_stdlib.hpp>#include<Windows.h>

std::string helloWorld(const std::string &t_name)
{
    return "Hello " + t_name + "!";
}
 int main()
{
    chaiscript::ChaiScript chai;
    SecureZeroMemory(&chai,sizeof(chai));
    chai.add(chaiscript::fun(&helloWorld),
        "helloWorld");

    chai.eval("puts(helloWorld(\"Bob\"));");


 return 0;
}

 if i add

<iostream.h>


then error at

line 516 load_module("chaiscript_stdlib-" + version());


Can you please help me out here.. I spent two days just to download
visual studio 2013 and its update 4.I dont want it to go to waste



Thanks

**Comment by zwparchman** [comment]
Changing the SecureZeroMemory to a memset let it compile in linux and it had a runtime error. Removing the zeroing fixes this.

**Comment by lefticus** [comment]
Why are you trying to overwrite the memory for ChaiScript immediately after creating the engine?

**Comment by deltamish** [comment]
I tried removing the securezeromemory
but still

execption at 795
throw chaiscript::exception::load_module_error("Unable to find module: " +
t_module_name + " Errors: " + errstring);

Please do help me out

**Comment by lefticus** [comment]
The entire error message from that exception would be helpful, but it would seem you are trying to use ChaiScript without providing it with its standard library.

Please see the examples:

Notice the description of this example says "Note that this example relies on being able to find the ChaiScript Stdlib module, precompiled in a known location."

http://chaiscript.com/examples.html#ChaiScript_Basic_Example

If you want to compile ChaiScript standard library into your program, which is generally recommended, use this example instead:

http://chaiscript.com/examples.html#ChaiScript_Compiled_in_Stdlib_Example

See the difference here, when constructing ChaiScript:

```
chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
```

**Comment by deltamish** [comment]
Wow thanks.. It worked...
Can you please How do recompile the stdlib in MSVC so that i can link to
that dll . so that i can have faster compile times....

Thanks

**Comment by lefticus** [comment]
This is how I recommend doing it. With 3 files .cpp files. One that compiles the stdlib, one that compiles the chaiscript runtime and one that compiles your specific bindings.

See here for an example:

https://github.com/ChaiScript/Spiced
