### ISSUE TITLE
Integer constants for (u)int8_t and (u)int16_t

### ISSUE THREAD

**Issue by 0xc0dec** [ChaiScript/ChaiScript#192]
Currently the following code fails to compile:
```
var a = U16Array();
a.push_back(1u);
```
with an error
```
Error: "Error with function dispatch for function 'push_back'" With parameters: (U16Array).(const uint32_t) during evaluation at (...)

  12 overloads available:
      (string).(char)
      (ByteArray).(const uint8_t)
      (U16Array).(const uint16_t)
      (S16Array).(const int16_t)
      (U32Array).(const uint32_t)
      (S32Array).(const int)
      <output omitted>
      (Object).(Object) : call_exists(push_back_ref, container, x)
          Defined at (standard prelude 122, 3)
```
I have my array types defined as follows:
```
engine->add(bootstrap::standard_library::vector_type<std::vector<uint8_t>>("ByteArray"));
engine->add(bootstrap::standard_library::vector_type<std::vector<uint16_t>>("U16Array"));
engine->add(bootstrap::standard_library::vector_type<std::vector<int16_t>>("S16Array"));
engine->add(bootstrap::standard_library::vector_type<std::vector<uint32_t>>("U32Array"));
engine->add(bootstrap::standard_library::vector_type<std::vector<int32_t>>("S32Array"));
```
I've checked out the source code in `chaiscript_parser.hpp` (`buildInt` function) and it seems like integer types with size <= 4 bytes are simply not supported and don't have special suffixes like "u", "ul", etc.. Having that support would be nice.

**Comment by lefticus** [comment]
What you've uncovered is an issue in the function `push_back`.

 * Because `Vector` (aka `std::vector<Boxed_Value>`) would naturally contain references to objects instead of copies, we've made the decision to wrap `push_back` to something that manually calls a clone.
 * Because you are passing an integer instead of the exact type the overload resolution is failing as it tries to find the exact version of `push_back` you want to call.
 * I don't have `short` or `byte` suffixes because C++ doesn't, and I modeled the suffixes it supports.

So, you can get moving forward by doing:

```
a.push_back(uint16_t(1u));
```

And also, I can fix the `push_back` wrapper function so that's not necessary.

**Comment by 0xc0dec** [comment]
I ended up fixing the parser and the `buildInt` function in particular to support those suffixes and parse integers of the required types. Maybe it's a hack, so I'm looking forward to seeing your solution :)

**Comment by lefticus** [comment]
What suffixes did you add? Is it worthy of a pull request?

**Comment by lefticus** [comment]
I just double checked the C++ standard and I don't see any standard suffix for < int sizes.

**Comment by 0xc0dec** [comment]
Well, since I'm not in charge of the language design and I don't see any problems with using suffixes that are non-existent in C++ I just added "s" for 2-bytes "short" and "ss" for 1-byte :) Again, it was mostly a hack to check if I can fix the engine, I ended up using your solution with type casting.

**Comment by lefticus** [comment]
I actually fixed the bug in the last couple of commits here. I'd be reluctant to define 's' to be 2 bytes since 'short' can have different meanings on different platforms.

But anyhow, the issue is fixed on develop now.
