### ISSUE TITLE
Can't represent 64-bit int using binary literal

### ISSUE THREAD

**Issue by RyokoAkizuki** [ChaiScript/ChaiScript#212]
I'm trying to store some data in binary literals, while they will be narrowed into 32-bit integers.
For example, 
```C++
if(0b1111111111111111111111111111111111111111111111111111111111111111 != 0xFFFFFFFFFFFFFFFF)
{
    print(0b1111111111111111111111111111111111111111111111111111111111111111.to_string());
    print((0b1111111111111111111111111111111111111111111111111111111111111111 >> 31).to_string());
}
```
gives out:
> 4294967295
> 1

**Comment by lefticus** [comment]
Looking at the parser, binary literals are handled differently than Hex, Dec, and Oct. I will fix it so they are handled exactly the same, and the same as the C++ standard. So once this issue is closed, expect to be able to do `u`, `l`, `ll`, `ull` suffixes as well and expect the binary literal string to be automatically sized, just as in compiled C++.

**Comment by lefticus** [comment]
This should be fixed on `develop` now.
