### ISSUE TITLE
Broken local variables in dispathkit with MSVC 2015 Update 3

### ISSUE THREAD

**Issue by ELynx** [ChaiScript/ChaiScript#279]
Compiler: Microsoft Visual Studio Community 2015 Version 14.0.25424.00 Update 3
Operating System/Architecture: Windows 10 64 bit, similar issue on Windows 7 64 bit

For dispatchkit.hpp, function `function_less_than`, type info for Boxed_Value and Boxed_Number is stored for comparison in static local variables:
`static const auto boxed_type = user_type<Boxed_Value>();`
`static const auto boxed_pod_type = user_type<Boxed_Number>();`
With given compiler such variables are sometimes not initialized, which leads to access to null pointer in this check:
`if (lt.bare_equal(boxed_type))`
`...`
This happens in release build only with optimizations.

Since this is not a bug in code as it is, I think this behavior could be placed in conditional compilation block.
`ifdef MSVC`
`const auto ...`
`else`
`static const auto ...`
`endif`
Another solution - move variables out of function local scope.

**Comment by ELynx** [comment]
Was looking through code history and found `CHAISCRIPT_HAS_MAGIC_STATICS`. Looks like some issues were encountered before.

**Comment by lefticus** [comment]
Your most recent comment implies to me you are using the most recent `develop` branch? `CHAISCRIPT_HAS_MAGIC_STATICS` should still be in the last release version of ChaiScript, because MSVC did not support thread safe static initialization.

That said, this would have been a corner case were you to access the function `function_less_than` from two different threads for the first time at the exact same time.

So, I need more information:

1. What branch / version are you using?
2. Does the issue go away if you try the last release version https://github.com/ChaiScript/ChaiScript/releases/tag/v5.8.3 ?
3. Did this issue occur with VS 2015 Update 2?
4. Are you using multiple threads?
5. Can you provide a complete example that exercises this bug?

Thank you

**Comment by ELynx** [comment]
1. I use develop, commit 176d608bb44149210ad25f6456a2e585db71c584
2. I tried 5.8.3 + parser from develop, looks like problem is gone. I include chaiscript_defines, then undefine CHAISCRIPT_HAS_MAGIC_STATICS, and then include the rest of necessary files.
For now - this is what I basically do manually in my source tree with develop, I went over code and removed static where it was troublesome.
3. Sorry, cannot check. I already have Update 3 and cannot roll it back. But as far as I remember there were no problems when I used U2/U1/RC; but then I used 5.8.2 and earlier.
4. I do, I use exactly two threads, initializing them one by one. Error happens on 1st thread initialization, this happens to be main thread for application. 2nd thread is not started until init for 1st is ready.
5. Sorry, I cannot. I tried to make simple example to reproduce bug, and debug it myself, but it happens only in whole project.

For now, I think problem lies in combination of chaiscript and my project's code, plus overall instability of MSVC 2015 U3, even with two latest patches; so, this is not an issue of chaiscript in itself.

**Comment by lefticus** [comment]
I know there have been some bugs reported in the most recent optimization changes for U3, so it's a good possibility that it will be fixed in the next update of VS... Ultimately that code should end up as `constexpr` not just `static const` but the develop branch is definitely in a state of flux right now. I'm hoping within the next month to start bringing all together again for a major release.
