### ISSUE TITLE
Compiling a script once and invoking it many times

### ISSUE THREAD

**Issue by n-ham** [ChaiScript/ChaiScript#516]
I have found [this](https://stackoverflow.com/questions/37668426/can-i-parse-compile-a-chaiscript-script-once-and-invoke-it-many-times) stackoverflow post which seems to indicate that I might be able to do this, however I don't seem to be able to work out how to do it. How do I take an `std::function` to the result so that I can invoke that? A simple code example would be awesome, thanks!

**Comment by n-ham** [comment]
I have tried for example `auto chaiScriptFn = chai.eval<std::function<bool()> >("print(y)");` however I get the following error:

	terminate called after throwing an instance of 'chaiscript::exception::bad_boxed_cast'
	  what():  Cannot perform boxed_cast: v to: St8functionIFbvEE
	Aborted (core dumped)

**Comment by totalgee** [comment]
You're trying to cast something to a function which isn't a function (`print(y)` is not a function). On the other hand:

```chaiscript
fun(y) { print(y) }
```
**is** a function (lambda), which you should be able to cast to a compatible `std::function` object in C++. But you also need to get the right signature. My example above couldn't be cast to `std::function<bool()>` either, because it doesn't return `bool` and it also takes an (arbitrary type) argument. But it **could** be cast to `std::function<void(Boxed_Value)>`.
